version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "./manage.py runserver 0.0.0.0:8000"
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/code
